name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest build
      - name: Build wheel/sdist
        run: python -m build
      - name: Import smoke test
        run: python - <<'PY'
          import importlib, sys
          try:
              importlib.import_module("deeppid")
              print("Import OK")
          except Exception as e:
              print("Import failed:", e)
              sys.exit(1)
          PY
                - name: Run tests (if any)
                  shell: bash
                  run: |
                    if compgen -G "tests/**/*.py" > /dev/null || compgen -G "tests/*.py" > /dev/null; then
                      pytest -q
                    else
                      echo "No tests found, skipping pytest."
                    fi
