name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest build

      - name: Build wheel/sdist
        run: python -m build

      - name: Import smoke test
        shell: bash
        run: |
          python - <<'PY'
          import importlib, sys
          try:
              importlib.import_module("deeppid")
              print("Import OK")
          except Exception as e:
              print("Import failed:", e)
              sys.exit(1)
          PY